[project]
name = "evolutions--pso-2d-py"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "gideonoludeyi", email = "49620086+gideonoludeyi@users.noreply.github.com"},
]
dependencies = [
    "numpy>=1.26.4",
    "matplotlib>=3.8.4",
    "imageio>=2.34.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
pso = "evolutions_pso_2d_py:main"

[tool.pdm]
distribution = true
